### ISSUE TITLE
adding multiple file after a first upload not working

### ISSUE THREAD

**Issue by mastermind1981** [Wildhoney/ngDroplet#18]
Hello,

After making a first upload ( one or multiple file) when i try to make a second one, if i select and add multiple files they are not added. 

When i do the same thing with individual files it works.

I'm using dropletUploadMultiple directive.

You can test it on the demi page.

**Comment by Wildhoney** [comment]
Thanks @mastermind1981 :+1: It was happening when you selected the same set of files to upload, which meant the `onchange` event listener wasn't firing because *strictly* speaking the values didn't change. [Solution](https://github.com/Wildhoney/ngDroplet/commit/285a1d30fccc7a4f7caa320aa8ade054cdfd701e) was to reset the value to `null` when the user clicks on the element.

Please give it a whirl now.

**Comment by mastermind1981** [comment]
hello, 

It works.
By the way you have done a good job may be you shoud make some article about ngdroplet in the angular eco system.

I have renamed locally the directive for progress bar to droplet progress because a of a conflict. May be it should be renamed.

Thank you

**Comment by Wildhoney** [comment]
Thanks! Where would you recommend me writing an article?

**Comment by mastermind1981** [comment]
http://www.sitepoint.com/
