### ISSUE TITLE
use multiple as simple uploads in a form

### ISSUE THREAD

**Issue by romain10009** [Wildhoney/ngDroplet#26]
is there a way to put two droplets in a form, along other input fields and to upload all the files, and the form data with them when submitted through angular?

**Comment by Wildhoney** [comment]
I've never tried, but I don't see why not. Use the `getFiles` method to bring back all of the files, and then construct your own `FormData` object using that data, plus your data from the form.

**Comment by romain10009** [comment]
Yes, ok that's what i thought, building it by hand, i expected there might be an easyer way. I will give it a try and let you know!

**Comment by romain10009** [comment]
I thought about the problem once more, and found a simple sollution : Instead of sending everything ( formdata with files), i will send text inputs first, wait for response, send files, done. Easy. I didnt switch my brain to asynchronous : )

**Comment by Wildhoney** [comment]
Aah! Perfect :+1: Glad you solved it :)

**Comment by ggoforth** [comment]
@Wildhoney no need to reopen this, but had a question, when I drop two files on a droplet it's doing two calls to my api for uploading, once for each file.  Is this expected, or should both files be sent in one request?  I'm trying to emulate a github style file upload, drag image(s) to the droplet, drop, auto upload to s3 and add markdown into the body of a text input. My controller code looks like:

```
    /**
     * The options for the droplet.
     *
     * @type {{}}
     */
    $scope.dropletInterface = {};

    /**
     * When dropping is bootstrapped...
     */
    $scope.$on('$dropletReady', () => {
      $scope.dropletInterface.allowedExtensions(['png', 'jpg', 'bmp', 'gif']);
      $scope.dropletInterface.setRequestHeaders({'Authorization': `Bearer ${User.currentUserToken}`});
      $scope.dropletInterface.setRequestUrl(`${URLS.API}/github/upload`);
      $scope.dropletInterface.useArray(false);
      $scope.dropletInterface.defineHTTPSuccess([/2.{2}/]);
    });

    /**
     * When a file is added, upload it right away...
     */
    $scope.$on('$dropletFileAdded', () => {
      if ($scope.dropletInterface.isReady()) {
        $scope.dropletInterface.uploadFiles();
      }
    });

    /**
     * When the droplet has finished uploading...
     */
    $scope.$on('$dropletSuccess', (event, res, files) => {
      if (!this.reply.body) this.reply.body = '';

      let mdFiles = '';

      _.each(files, file => {
        mdFiles += `![${file.file.name}](${URLS.S3ASSETSBUCKET}/${file.file.name})\r\n`;
      });

      this.reply.body += mdFiles;
    });
```

In my case `$dropletSuccess` and `$dropletFileAdded` is called multiple times.  

<img width="307" alt="screenshot 2016-03-06 16 00 07" src="https://cloud.githubusercontent.com/assets/1167712/13558244/9b86c9a8-e3b4-11e5-9607-cf2d9f7a871a.png">

That was the result of dropping two files on a droplet area.  Thanks again @Wildhoney!

**Comment by Wildhoney** [comment]
I'm unable to replicate &mdash; for me dragging two files invokes `on-add` twice, and `on-success` once. I'd be worried if you're seeing such results.

Open [the example](http://ng-droplet.herokuapp.com/) and put a breakpoint on `Default.js` line `43` &mdash; and then upload a file. You should see it's only invoked once per upload &mdash; even with a set of files.

**Comment by ggoforth** [comment]
@Wildhoney gotcha, I'm looking into it.  I wonder if this has anything to do with registering my events (`$dropletReady`, `$dropletFileAdded` and `$dropletSuccess`) in a custom directive controller instead of the link?  I wouldn't think that would matter, but I'm now trying to figure out why it's being called so many times.  I have multiples of this directive on the page at any one time, but it seems like I've got this setup in a standard fashion.  At any rate, thanks for being so responsive on the issues, I certainly appreciate it!

**Comment by ggoforth** [comment]
Ah, now I'm getting somewhere...there is a correlation between how many of my custom directives I have on the page, and how many times the event listeners get called...the plot thickens :)

**Comment by Wildhoney** [comment]
Haha... [Use the attributes instead](https://github.com/Wildhoney/ngDroplet/commit/ee68ba8caee04b878237964fd5caa09974d3ab15).

See: https://github.com/Wildhoney/ngDroplet/issues/49
And related JSFiddle: https://jsfiddle.net/142voLtk/

**Comment by ggoforth** [comment]
Sweet, will give that a whirl and report back.  Thanks @Wildhoney!

**Comment by Wildhoney** [comment]
@ggoforth no problem :+1: Let me know if you have any further troubles.

**Comment by ggoforth** [comment]
I think the root issue is that I'm uploading during the onAdd callback.  Since onAdd is called once for every dropped file (IE I dropped three files at once, it's called one time with each file) then I'm getting multiple onSuccess callbacks (presumably since I called uploadFiles multiple times).  If my understanding is then correct, it seems like I need some kind of `afterOnAdd` that would be called after the drop has occurred, and after the individual onAdd events so that calling `uploadFiles` would then upload all three at once.  I'm gonna try and whip up a fiddle demonstrating the issue, I just can't seem to dial this in quite right.  I'll also move the conversation to another issue so as to not muck this one up any more.  Thanks @Wildhoney.

**Comment by Wildhoney** [comment]
`onAdd` is behaving correctly &mdash; once per file, and it appears as though `onSuccess` is too &mdash; as that's called for each upload. In the example all files are uploaded at once, rather than individually.

**Comment by ggoforth** [comment]
Yup, that's the functionality I'm looking for, all at once, but I need it AFTER `on-add` has done it's thing.  So it would call on-add for each file, and then it would call some other event, like 'afterOnAdd` so I can hook into that for uploading all files at once immediately after a drop, so I don't have to have a button to click to say, "now upload all the files".

**Comment by Wildhoney** [comment]
Happy to merge something like that if you can put together a PR @ggoforth :+1:
