### ISSUE TITLE
TypeError: Cannot read property 'allowedExtensions' of undefined

### ISSUE THREAD

**Issue by thegreatmichael** [Wildhoney/ngDroplet#30]
I was trying to follow the example in the source and the readme. for some reason, in my `$scope.$on('$dropletReady', function whenDropletReady() {`, `$scope.uploader` is undefined. (or, if i set it to `{}` as in the example, it remains an empty dict.

What am I missing? 

My source is here:
https://github.com/thegreatmichael/case-of-fabulous
https://github.com/thegreatmichael/case-of-fabulous/blob/master/app/views/main.html
https://github.com/thegreatmichael/case-of-fabulous/blob/master/app/scripts/controllers.main.js

I edited ng-droplet.js to `console.log($scope.interface);` right before `$rootScope.$broadcast('$dropletReady');` and it seems to be a properly defined object, but somehow it's not making it back to the property on `MainCtrl`

**Comment by Wildhoney** [comment]
@thegreatmichael Sorry, your [`controllers.main.js`](https://github.com/thegreatmichael/case-of-fabulous/blob/master/app/scripts/controllers.main.js) doesn't exist any more, so I can't exactly what you're doing.

I assume your `$scope.uploader` is the `$scope.interface` from the README. In that case, you'll need to ensure that you're passing your `$scope.uploader` into the `ng-model` in your template:

```html
<droplet ng-model="uploader"></droplet>
```

Please let me know if that works for you :+1:

**Comment by thegreatmichael** [comment]
I apologize for the typo: it's been corrected to https://github.com/thegreatmichael/case-of-fabulous/blob/master/app/scripts/controllers/main.js

the relevant (I think) snippets are: 

MainCtrl (indicated in my app config `app.js` to be the controller that uses template `main.html`)

    angular.module('caseOfFabulousApp')
      .controller('MainCtrl', function ($scope, $timeout) {
        
        ...

        // $scope.uploader = {}; //doesn't seem to help whether I define this or not

        $scope.$on('$dropletReady', function whenDropletReady() {
          // Directive's interface is ready to be used...
          console.log('droplet ready!!!');
          $timeout(function () {
            $scope.$apply(function () {
              console.log('timedout');
              // console.log($scope);
              console.log($scope.uploader);
              $scope.uploader.allowedExtensions(['png', 'jpg', 'bmp', 'gif']);
            });
          }, 2000);
        });
    });

`main.html`

    ...
    
    <droplet ng-model="uploader">
    </droplet>
    
    ...

thanks for any suggestions. for now, i figured out a workaround, i modified the ng-droplet src locally to change 

   $rootScope.$broadcast('$dropletReady');

to

    $rootScope.$broadcast('$dropletReady', $scope.interface);

so I can now expect the interface to be passed in directly to my $dropletReady callback, where i can assign it to the local (`$scope`) variable.

**Comment by Wildhoney** [comment]
I could make that change in the source itself, because it would be a non-breaking change, but that doesn't solve the actual issue. I assume the `uploader` in the `ng-model` attribute isn't the same `uploader` that you're using in the controller.

On line <kbd>701</kbd> is where the [`$scope.interface` is bound](https://github.com/Wildhoney/ngDroplet/blob/master/components/ngDroplet.js#L701) but that's simply using the `ng-model` attribute from line <kbd>29</kbd>.

**Comment by Wildhoney** [comment]
On the [following line](https://github.com/thegreatmichael/case-of-fabulous/blob/master/app/index.html#L34) move your `ng-controller` into the **views/main.html** template, because an `ng-include` implicitly creates a child scope.

```html
<div class="jumbotron" ng-controller="MainCtrl">
  <h1>'Allo, 'Allo!</h1>
  <p class="lead">
    ...
```

Alternatively you can use the [controller as syntax](http://toddmotto.com/digging-into-angulars-controller-as-syntax/) and leave the `ng-controller` where it is.

...or use `$parent`, or use an `Object` to prevent objects being defined on the incorrect scope.
