### ISSUE TITLE
Is it possible to make ngDroplet to upload only one image

### ISSUE THREAD

**Issue by raimonbosch** [Wildhoney/ngDroplet#36]
I want to use ngDroplet in an application when you only need to upload one image, and not many. But I could not find an option to emulate this behavior. I would like to see that when I reupload an image, the old one is replaced.

Is it possible to accomplish this behavior? If not, which changes should we perform on the code?

**Comment by Wildhoney** [comment]
It's entirely up to your backend to overwrite the previously uploaded file for any given user.

However, for uploading only a single image, I suppose we need to implement `maximumValidFiles` as in the Ember equivalent &mdash; [`EmberDroplet`](https://github.com/Wildhoney/EmberDroplet#options).

Let me take a look.

**Comment by raimonbosch** [comment]
Thanks! I have tested the maximum and it works. But if you drop a second image does not replace the previous. I guess I should handle that from my backend.

**Comment by Wildhoney** [comment]
It would also be nice if we could provide a strategy to `ngDroplet` to tell it what it should do in such circumstances. By default it could simply set the additional files as `INVALID`, or it could start invalidating files added earlier to make room for new files.

Thoughts?

**Comment by mwgi2005** [comment]
Yes You can upload one image and 10 at the same time via ngDroplet.

Since I'm using Node and Express and multer for file handling, all I had to do is to define the requestURL in ngDroplet Controller:

$scope.interface.setRequestUrl('http://localhost:3000/api/upload');

and the request will be sent to Node API, just define multer on top of your API.

router.use(multer({ dest: __dirname + '/public/uploads' }));
   router.post('/upload', function(req, res)
    {        res.json({"filename": req.files.file});
    
    });

and thats it file upload.... also you can fetch the filenames from response if you want to insert it into DB.
